# Домашнее задание

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [5]:
import numpy as np

In [6]:
n = int(input('Введите число N = '))
np.arange(n)[::-1]

Введите число N = 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [8]:
n = float(input('Введите число N = '))
array2 = np.diag(np.arange(n, -1, -1), k = 0)
array2 

Введите число N = 10


array([[10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
print('Сумма значений по диагонали = ', array2.sum())

Сумма значений по диагонали =  55.0


# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [12]:
a_left = np.array([[4,2,1], [1, 3, 0], [0, 5, 4]])  
a_right = np.array([4, 12, -3])  

In [13]:
from numpy import linalg

In [14]:
linalg.solve(a_left, a_right)

array([ 0.46666667,  3.84444444, -5.55555556])

In [15]:
#ручная проверка
4*linalg.solve(a_left, a_right)[0] + 2*linalg.solve(a_left, a_right)[1] + linalg.solve(a_left, a_right)[2]

4.0

In [16]:
#проверка
np.allclose( np.dot(a_left, linalg.solve(a_left, a_right)), a_right)

True

# Задание 4
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [18]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [20]:
#На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [21]:
def cosin(a, b):
    """ Подсчет косинуса угла между векторами а и b по их координатам,
        расчет длин векторов делается с использовании фукнции linalg.norm()"""
    #расчитаем длины векторов 
    aNorma = np.linalg.norm(a) 
    bNorma = np.linalg.norm(b)
    
    return np.dot(a, b)/(aNorma*bNorma)

In [23]:
d = ({})
for k,i in enumerate(users_stats):
    cosine_imilarity = cosin(i, next_user_stats)
    d.update({k+1:cosine_imilarity})
most_similar_user = max(d.items(), key=lambda x: x[1])
print(most_similar_user)
most_similar_user_id = max(d, key=d.get)
print ('Самый похожий пользователь с ID = ', most_similar_user_id)

(8, 0.9486832980505138)
Самый похожий пользователь с ID =  8
