In [1]:
import numpy as np

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = int(input('Введите число N = '))
np.arange(n)[::-1]

Введите число N = 7


array([6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [18]:
n = int(input('Введите число N = '))
b = np.diag(np.arange(n)[::-1], k=0)
b

Введите число N = 12


array([[11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [19]:
# Сумма значений на диагонали
np.trace(b)

66

# Задание 3
Решите систему уравнений:
#### 4x + 2y + z = 4
#### x + 3y = 12
#### 5y + 4z = -3

In [5]:
a = np.array( [ [4, 2, 1],[1, 3, 0],[0, 5, 4] ])
b = np.array( [4, 12, -3])

In [6]:
from numpy import linalg

In [7]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b)

True

# Задание 4

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [10]:
#новый покупатель
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [11]:
#рассчитаем скалярное произведение между векторами старых и нового покупателей
np.dot(users_stats, next_user_stats)

array([1, 5, 2, 5, 2, 0, 0, 3, 0, 0])

In [12]:
# далее, рассчитаем косинусное сходство
#импортируем matplotlib.pyplot

import matplotlib.pyplot as plt

In [13]:
#формула для подсчета косинусного угла
def cosine_1 (users_stats, next_user_stats):
    '''
    Подсчет косинуса угла между векторами массива users_stats и next_user_stats по их координатам
    '''
    #длины векторов
    aLength = np.linalg.norm( users_stats )
    bLength = np.linalg.norm( next_user_stats )
    
    return np.dot(users_stats,next_user_stats) / (aLength * bLength )

In [14]:
cos_array = cosine_1 (users_stats, next_user_stats)

In [15]:
# Найдем максимальное значение сходства для дальнейшей рекомендации
recom = max(cos_array)
recom

0.2344036154692477

In [16]:
for i, cos in enumerate(cos_array):
    if cos == recom:
        print('похожий пользователь id =',i+1, ', косинусное сходство =', cos)

похожий пользователь id = 2 , косинусное сходство = 0.2344036154692477
похожий пользователь id = 4 , косинусное сходство = 0.2344036154692477
